runtime: python39

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 0.25

env_variables:
  ENVIRONMENT: production
  DEBUG: 'false'